### ISSUE TITLE
mgf read issue (RTINMINUTES)

### ISSUE THREAD

**Issue by amason30** [tidymass/masstools#2]
Hi, I am really excited about the TidyMass ecosystem of packages and the work your group has done. 

We have been working with untargeted metabolomics data from a Bruker machine that has been preprocessed in and exported from Metaboscape. I have both a feature table (expression_data) and an .mgf file with MS2 scans. I am interested in importing my data into R using your ecosystem of packages to create a `mass_dataset` object. I am able to import the feature table and create my `mass_dataset` object, however I am unable to import the MS2 data. I think this is because my .mgf file reports retention time in minutes under "RTINMINUTES".  Because of this tag, we were
unable to read our mgf file and forced to convert the RTINMINUTES to RTINSECONDS and leads to list of length 0 when supplying my file to the `read_mgf()`. Due to this, our data had issues matching using the mz_rt_match function. This is mainly due to floating point precision issue.

I believe this is linked to lines 52 - 55 of the read_mgf.R script:

```      
info.rt <-
        lapply(mgf.data, function(x) {
          grep("^RTINSECONDS|RETENTIONTIME", x, value = TRUE)
        })
```

The function isn't seeing my rt info because it is not stored as "RTINSECONDS" or "RETENTIONTIME". As we work to to integrate our data to use your packages, would you be interested a pull request to add this functionality and expand for Metaboscape users?

**Comment by jaspershen** [comment]
Thanks, amason30. Yes, please make the pull request and I will accept it. Thank you.

**Comment by jaspershen** [comment]
Done!
